version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=repo
      - POSTGRES_PASSWORD=repo
      - POSTGRES_DB=store
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
volumes:
  db:
    driver: local
